docker_hub_auth: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62363261376466613532356230653439616266383463373361303161316538666631613531623763
          6165323965303136663430626231353337616464653665330a633563623532646135393736333831
          34323562646435383339393339663739333064333263303839633162386463366465323830316432
          3663383130373264610a323764326132393135383739306266663237643162363561616238363335
          64636332316136343634363439353730363632653332376132326364366436313836643239313137
          31393237343237663764326637613435313163643737353061383430336261356339626566346364
          64626337323034313435643166303733326361356236613137656435306233333032373335306338
          31623962646230623639
